# Generated by Django 2.2.24 on 2022-10-20 10:54

from django.db import migrations


def is_flat_in_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20221020_1240'),
    ]

    operations = [
        migrations.RunPython(is_flat_in_new_building),
    ]
