# Generated by Django 4.1.2 on 2022-10-21 16:06

from django.db import migrations
import phonenumbers

def change_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all().iterator()
    for flat in flats:
        phone_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phone_number):
            flat.owner_pure_phone = phonenumbers.format_number(phone_number, phonenumbers.PhoneNumberFormat.E164)
        else:
            flat.owner_pure_phone = ''
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(change_phone_number),
    ]
